// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzX64POXhv9xhT7qTLi6VRWNqfnob46Y',
    appId: '1:799945981526:web:bbc1609801106f82da45f7',
    messagingSenderId: '799945981526',
    projectId: 'astarte-odtu',
    authDomain: 'astarte-odtu.firebaseapp.com',
    storageBucket: 'astarte-odtu.appspot.com',
    measurementId: 'G-4MG6YG58QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaulmdKFCqLB-eK5L3EIIASJAx6haGCb8',
    appId: '1:799945981526:android:bac719d79a9c18ecda45f7',
    messagingSenderId: '799945981526',
    projectId: 'astarte-odtu',
    storageBucket: 'astarte-odtu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5SgfTE9zj_W18pWOU4hg2kw9ULVfQUg',
    appId: '1:799945981526:ios:abbdc5abf1fa7099da45f7',
    messagingSenderId: '799945981526',
    projectId: 'astarte-odtu',
    storageBucket: 'astarte-odtu.appspot.com',
    iosClientId: '799945981526-a5fn4nvko84igb3ni2298hqgael31vgj.apps.googleusercontent.com',
    iosBundleId: 'app.astarte.astarte',
  );
}
