# Generated by Django 4.1.3 on 2023-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Watering Event'), (1, 'Frost Event')])),
                ('date', models.DateTimeField()),
                ('importance', models.IntegerField(choices=[(0, 'Critical Importance Event'), (1, 'Moderate Importance Event'), (2, 'Safe Event')])),
            ],
        ),
    ]
